### ISSUE TITLE
Subfolder "archive" not existent

### ISSUE THREAD

**Issue by DirkSeif** [jgiannuzzi/taiga-contrib-saml-auth#2]
Hi 
i want to download the "tar.gz" as described in the installation manual , but the "tar.gz" file is not available.

Can you please provide this file or tell me which file i need instead of this.

Best regards

**Comment by jgiannuzzi** [comment]
What is the output of "pip show taiga-contrib-saml-auth" in your taiga-back virtualenv?

The current version is 1.0.1, so the URL of the tarball is https://github.com/jgiannuzzi/taiga-contrib-saml-auth/archive/1.0.1.tar.gz
