### ISSUE TITLE
clarification requested, is this a saml provider, or a saml consumer?

### ISSUE THREAD

**Issue by ghost** [jgiannuzzi/taiga-contrib-saml-auth#8]
I was hoping to join a taiga instance to a saml provider, however this setup is far more complex that previous saml set ups I've done (not that i've done many) and I noticed you listed a saml hosting service as an upstream source, so i wanted to ask for clarification before proceeding to use this. Thank you!

**Comment by jgiannuzzi** [comment]
Sorry for the very late reply!

This is a SAML Service Provider, which "consumes" an assertion returned by a SAML Identity Provider. I guess this is what you meant by "SAML consumer".
